on: [push]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change README
        run: cat README.md | sed 's/```text/```yaml/' | tee README.md
      - name: Commit results
        run: |
          git commit README.md -m 'Change README contents' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
