name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '*/20 * * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
      - uses: actions/checkout@v2
      - name: Change README
        run: cat README.md | sed 's/```text/```yaml/' | tee README.md
      - name: Commit results
        run: |
          git commit README.md -m 'Change README contents' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
